FROM pdal/pdal

# ENV http_proxy <HTTP_PROXY>
# ENV https_proxy <HTTPS_PROXY>
# ENV http_proxy http://192.168.4.9:3128
# ENV https_proxy http://192.168.4.9:3128


WORKDIR /usr/src/app
COPY ./ /usr/src/app/georender/


RUN apt-get update && apt-get install -y git wget jq p7zip-full --assume-yes


RUN cd /tmp/ \ 
    && wget https://go.dev/dl/go1.20.5.linux-amd64.tar.gz \
    && rm -rf /usr/local/go && tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz

RUN cd /usr/src/app/ \
    && git clone https://github.com/mfbonfigli/gocesiumtiler.git \
    && cd gocesiumtiler && export CGO_LDFLAGS="-g -O2 -lm" && /usr/local/go/bin/go build


RUN apt-get update \
    && pip install  --upgrade pip  \
    && /opt/conda/bin/pip3 install  geopandas


# ENTRYPOINT [ "/bin/bash", "-l", "-c" ]