FROM pdal/pdal

# ENV http_proxy <HTTP_PROXY>
# ENV https_proxy <HTTPS_PROXY>
# ENV http_proxy http://192.168.4.9:3128
# ENV https_proxy http://192.168.4.9:3128


WORKDIR /usr/src/app
COPY ./ /usr/src/app/georender/
COPY ./run.sh /usr/src/app/georender/run.sh
RUN   --mount=type=cache,target=/var/cache/apt apt-get update && apt-get install -y git wget jq p7zip-full --assume-yes

# Was needed for gocesiumtiler, using separate image for py3dtiles now
#RUN  --mount=type=cache,target=/var/cache/apt cd /tmp/ \ 
#    && wget https://go.dev/dl/go1.20.5.linux-amd64.tar.gz \
#    && rm -rf /usr/local/go && tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz
#
#RUN --mount=type=cache,target=/var/cache/apt cd /usr/src/app/ \
#    && git clone https://github.com/mfbonfigli/gocesiumtiler.git \
#    && cd gocesiumtiler && export CGO_LDFLAGS="-g -O2 -lm" && /usr/local/go/bin/go build


RUN --mount=type=cache,target=/var/cache/apt apt-get update \
    && pip install  --upgrade pip  \
    && /opt/conda/bin/pip3 install geopandas \
    && /opt/conda/bin/pip3 install -r /usr/src/app/georender/requirements.txt \
    && /opt/conda/bin/pip3 install pyproj


#ENTRYPOINT [ "/bin/bash", "-l", "-c" , "./usr/src/app/georender/run.sh" ]
