[tool.poetry] 
name="lidar-streamlit-app"
version="0.1.0"
description = "streamlit application for lidar HD demo"
authors=["Dhruv Malik"]

[tool.poetry.dependencies]
python = ">=3.8,<3.9.7 || >3.9.7,<4"
py3dtiles = ">=5.0.0"
streamlit = ">=1.24.0"
[tool.poetry.dev-dependencies]
