FROM python:3.11
WORKDIR /usr/app/
COPY . ./usr/app/bacalhau/
RUN pip3 install  --no-cache-dir --upgrade -r ./usr/app/bacalhau/requirements.txt
CMD ["uvicorn", "bacalau_script:app", "--host", "0.0.0.0", "--port", "8000"]

