[tool.poetry]
name = "bacalau-script"
version = "0.0.1"
description = "wrapper script on top of bacalau sdk to schedule the compute jobs of the given georendering pipeline"
readme = "./README.md"

[tool.poetry.dependencies]
python = "> 3.5"
