FROM confluentinc/cp-kafka


WORKDIR /usr/app/kafka/


COPY ./src/consumer/ /usr/app/kafka/
COPY ./src/producers/ /usr/app/kafka/
COPY ./src/requirements.txt /usr/app/kafka/
COPY ./src/kafka_config.py /usr/app/kafka/

RUN python3 -m pip install --upgrade pip
RUN  pip3 install -r /usr/app/kafka/requirements.txt

## installing the require
